/**
 * 通用颜色列表
 */
export const colorListGeneralData: Array<number> = [
  0xFF000000, // 黑
  0xFFFFFFFF, // 白
  0xFFFF0000, // 红
  0xFF00FF00, // 绿
  0xFF0000FF, // 蓝
  0xFFE0E0E0, // 银灰
  0xFF333333, // 深灰
  0xFF808080, // 中灰
  0xFFCCCCCC, // 浅灰
  0xFF4CAF50, // 翠绿
  0xFFFFC107, // 橙黄
  0xFFF44336, // 鲜红
  0xFF2196F3, // 天蓝
  0xFF1976D2, // 深蓝
  0xFFF5F5F5, // 烟白
  0xFF191919, // 炭黑
  0xFF00F5FF, // 绿松石
  0xFF6A5ACD, // 板岩蓝
  0xFF32CD32, // 酸橙绿
  0xFFFFD700, // 金
  0xFFFA8072, // 肉粉
  0xFFEE82EE, // 紫罗兰
  0xFF7EC0EE, // 天空蓝
  0xFF8B0000, // 深红
  0x00000000// 透明色
]

/**
 * 通用布尔值列表
 */
export const booleanListGeneralData: Array<boolean> = [true, false]

/**
 * 通用文本大小列表
 */
export const textSizeListGeneralData: Array<number> =
  [12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36]

/**
 * 通用文本行高列表
 */
export const textLineHeightListGeneralData: Array<number> =
  [12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36]

/**
 * 通用文本字间距列表
 */
export const textWordSpaceListGeneralData: Array<number> = [0, 0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

/**
 * 通用间距列表
 */
export const marginListGeneralData: Array<number> = [0, 5, 8, 10, 15, 20, 25, 30, 35, 40]

/**
 * 通用文本字体列表
 */
export const textTypefaceListGeneralData: Array<string> = ["HarmonyOS Sans", "Hei"]

/**
 * 加载每次间隔时间列表
 */
export const timeListGeneralData: Array<number> =
  [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500]

/**
 * 每次增量文本数量列表
 */
export const textNumberListGeneralData: Array<number> =
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 25, 30, 35, 40, 45, 50, 100, 150, 200]