/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */
package markdown.components

public class MarkdownAICacheConfiguration {
    let list1Components: ArrayList<ListAI1Data> = ArrayList<ListAI1Data>()

    let list2Components: ArrayList<ListAI2Data> = ArrayList<ListAI2Data>()

    let list3Components: ArrayList<ListAI3Data> = ArrayList<ListAI3Data>()

    let listItem1Components: ArrayList<ListItemAI1Data> = ArrayList<ListItemAI1Data>()

    let listItem2Components: ArrayList<ListItemAI2Data> = ArrayList<ListItemAI2Data>()

    let listItem3Components: ArrayList<ListItemAI3Data> = ArrayList<ListItemAI3Data>()

    let quote1Components: ArrayList<QuoteAI1Data> = ArrayList<QuoteAI1Data>()

    let quote2Components: ArrayList<QuoteAI2Data> = ArrayList<QuoteAI2Data>()

    let quote3Components: ArrayList<QuoteAI3Data> = ArrayList<QuoteAI3Data>()

    let paragraph1Components: ArrayList<MarkdownAIParagraph1Component> = ArrayList<MarkdownAIParagraph1Component>()

    let paragraph2Components: ArrayList<MarkdownAIParagraph2Component> = ArrayList<MarkdownAIParagraph2Component>()

    let paragraph3Components: ArrayList<MarkdownAIParagraph3Component> = ArrayList<MarkdownAIParagraph3Component>()

    let paragraph4Components: ArrayList<MarkdownAIParagraph4Component> = ArrayList<MarkdownAIParagraph4Component>()

    let heading1Components: ArrayList<MarkdownAIHeading1Component> = ArrayList<MarkdownAIHeading1Component>()

    let heading2Components: ArrayList<MarkdownAIHeading2Component> = ArrayList<MarkdownAIHeading2Component>()

    let heading3Components: ArrayList<MarkdownAIHeading3Component> = ArrayList<MarkdownAIHeading3Component>()

    let heading4Components: ArrayList<MarkdownAIHeading4Component> = ArrayList<MarkdownAIHeading4Component>()

    let table1Components: ArrayList<TableAI1Data> = ArrayList<TableAI1Data>()

    let tableRow1Components: ArrayList<TableRowAI1Data> = ArrayList<TableRowAI1Data>()

    let tableCell1Components: ArrayList<TableCellAI1Data> = ArrayList<TableCellAI1Data>()

    let indentedCode1Components: ArrayList<IndentedCodeAI1Data> = ArrayList<IndentedCodeAI1Data>()
}
