/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights resvered.
 */
package ohos_app_cangjie_entry

internal import ohos.router.*
internal import ohos.ability.*
internal import ohos.window.*
internal import ohos.prompt_action.*

internal import ohos.resource_manager.ResourceManager

internal import ohos.file_fs.*

internal import std.collection.*
internal import encoding.json.*

internal import cj_res_entry.app

internal import markdown.components.*
internal import markdown.core.*
internal import markdown.plugin.*